# Module: NumPy Assignments
## Lesson: NumPy

### Assignment 1: Array Creation and Manipulation
1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [1]:
import numpy as np

In [4]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# 1. Replace all the elements in the third column with 1
array[:, 2] = 1
print("Modified array:")
print(array)

# 2. Create a Numpy array of shape(4,4) with values from 1 to 16
array2 = np.random.randint(1, 17, size=(4, 4))
print("New array:")
print(array2)

#2. Replace the diagonal elements with 0
np.fill_diagonal(array2, 0)
print("Modified new array:")
print(array2)

Original array:
[[13  1 14  6  2]
 [ 3  6 17  9 20]
 [ 7 17  6 11  8]
 [ 5 15  3 20  2]
 [ 9  2 20  9 20]]
Modified array:
[[13  1  1  6  2]
 [ 3  6  1  9 20]
 [ 7 17  1 11  8]
 [ 5 15  1 20  2]
 [ 9  2  1  9 20]]
New array:
[[13  8  7 10]
 [ 5  5  8  8]
 [ 4  9  9  2]
 [14 12 14 14]]
Modified new array:
[[ 0  8  7 10]
 [ 5  0  8  8]
 [ 4  9  0  2]
 [14 12 14  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [8]:
### 1. Create a NumPy array of shape (6, 6) filled with random integers
array = np.random.randint(1, 36, size=(6, 6))
print("Original array:")
print(array)

# 1. Extract the sub-array consisting of 3rd to 5th rows and 2nd to fourth column
sub_array = array[2:5, 1:4]
print("Sub-array from the fourth column:")
print(sub_array)

# 2. Create a Numpy array of shape (5,5) with random integers
array2 = np.random.randint(1, 100, size=(5, 5))
print("New array:")
print(array2)

# 2. Extract the elements of the border
border_elements = array2[0, :]  # Top row
border_elements = np.concatenate((border_elements, array2[4, :]))  # Bottom row
border_elements = np.concatenate((border_elements, array2[1:4, 0]))  # Left column
border_elements = np.concatenate((border_elements, array2[1:4, 4]))  # Right column
print("Border elements:")
print(border_elements)

Original array:
[[12  8 18  5 34 20]
 [31  3  6 28 31 24]
 [10 26 21 28 11  3]
 [15 27 13 29 34 25]
 [15 20  6 29 18 33]
 [30  8  4 22  7 30]]
Sub-array from the fourth column:
[[26 21 28]
 [27 13 29]
 [20  6 29]]
New array:
[[71 97 63 28 17]
 [23 70 18 76 95]
 [11 98 14 44 35]
 [84 40 12 68 95]
 [87 95  6 26 80]]
Border elements:
[71 97 63 28 17 87 95  6 26 80 23 11 84 95 35 95]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [12]:
# 1. Create two Numpy arrays of shape (3,4) with random integers
array1 = np.random.randint(1, 51, size=(3, 4))
print("Array 1:")
print(array1)
array2 = np.random.randint(1, 51, size=(3, 4))
print("Array 2:")
print(array2)

# 1. Perform element-wise addition, subtraction, multiplication, and division
add_array = np.add(array1, array2)  
sub_array = np.subtract(array1, array2)
mul_array = np.multiply(array1, array2)
div_array = np.divide(array1, array2)   

print("Element-wise addition:")
print(add_array)
print("Element-wise subtraction:")
print(sub_array)
print("Element-wise multiplication:")
print(mul_array)
print("Element-wise division:")
print(div_array)


# 2. Create a Numpy array of shape (4,4) with random integers with values 1 to 16, Compute the row-wise and column-wise sums
array3 = np.random.randint(1, 17, size=(4, 4))
print("Array 3:")
print(array3)
row_sum = np.sum(array3, axis=1)
col_sum = np.sum(array3, axis=0)
print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(col_sum)


Array 1:
[[49 41  1 32]
 [39 50 18 37]
 [43 37  4 21]]
Array 2:
[[14 39 40 42]
 [27  6 14 31]
 [11  4 27 45]]
Element-wise addition:
[[63 80 41 74]
 [66 56 32 68]
 [54 41 31 66]]
Element-wise subtraction:
[[ 35   2 -39 -10]
 [ 12  44   4   6]
 [ 32  33 -23 -24]]
Element-wise multiplication:
[[ 686 1599   40 1344]
 [1053  300  252 1147]
 [ 473  148  108  945]]
Element-wise division:
[[3.5        1.05128205 0.025      0.76190476]
 [1.44444444 8.33333333 1.28571429 1.19354839]
 [3.90909091 9.25       0.14814815 0.46666667]]
Array 3:
[[12  3 14 15]
 [ 5  5  9  1]
 [16 14 12  8]
 [ 2 11  4 10]]
Row-wise sum:
[44 20 50 27]
Column-wise sum:
[35 33 39 34]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [14]:
# 1. Create a Numpy array of shape (5,5) with random integers
array4 = np.random.randint(1, 51, size=(5, 5))
print("Array 4:")
print(array4)

# 1. Compute the mean, median, and standard deviation and variance of the array
mean = np.mean(array4)
median = np.median(array4)
std_dev = np.std(array4)
var = np.var(array4)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", var)


# 2. Create a Numpy array of shape(3,3) with values from 1 to 9.
array5 = np.arange(1, 10).reshape(3, 3)
print("Array 5:")
print(array5)

# 2. Normalize the array (i.e scale the values to have a mean of 0 and a standard deviation of 1)
array5_normalized = (array5 - np.mean(array5)) / np.std(array5)
print("Normalized Array 5:")
print(array5_normalized)


Array 4:
[[ 8 11 24 38  5]
 [32 20 24 20 21]
 [17 37 23 50  6]
 [27 13  7 35 44]
 [16 26 25 10 35]]
Mean: 22.96
Median: 23.0
Standard Deviation: 12.008263821219119
Variance: 144.1984
Array 5:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array 5:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [17]:
# 1. Create a Numpy array of shape (3,3) with random integers
array6 = np.random.randint(1, 51, size=(3, 3))
print("Array 6:")
print(array6)

# 1. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting
array7 = np.random.randint(1, 51, size=(3,))
print("Array 7:")
print(array7)
result = array6 + array7
print("Result of broadcasting addition:")
print(result)


# 2. Create a Numpy array of shape (4,4) with random integers
array8 = np.random.randint(1, 51, size=(4, 4))
print("Array 8:")
print(array8)

# 2. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting
array9 = np.random.randint(1, 51, size=(4,))
print("Array 9:")
print(array9)
result2 = array8 - array9[:, np.newaxis]
print("Result of broadcasting subtraction:")
print(result2)

Array 6:
[[45 19 18]
 [46 37 45]
 [39 25 26]]
Array 7:
[ 1 16 22]
Result of broadcasting addition:
[[46 35 40]
 [47 53 67]
 [40 41 48]]
Array 8:
[[27 19 21  9]
 [ 3 20 15 41]
 [13 29  6 30]
 [11 13 49 32]]
Array 9:
[16 14 22 12]
Result of broadcasting subtraction:
[[ 11   3   5  -7]
 [-11   6   1  27]
 [ -9   7 -16   8]
 [ -1   1  37  20]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [20]:
# 1. Create a Numpy array of shape (3,3) representing a matrix
array10 = np.random.randint(1, 51, size=(3, 3))
print("Array 10:")
print(array10)

# 1. Compute the determinant, inverse, eigenvalues, and transpose of the matrix
det = np.linalg.det(array10)
print("Determinant:", det)
try:
    inv = np.linalg.inv(array10)
    print("Inverse:")
    print(inv)
except np.linalg.LinAlgError:
    print("Inverse: Not computable (matrix may be singular)")
eigenvalues, eigenvectors = np.linalg.eig(array10)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)
print("Transpose:")
print(array10.T)


# 2. Create two Numpy arrays of shape (2,3) and (3,2).
array11 = np.random.randint(1, 51, size=(2, 3))
print("Array 11:")
print(array11)
array12 = np.random.randint(1, 51, size=(3, 2))
print("Array 12:")
print(array12)


# 2. perform multiplication on these arrays 
result = np.dot(array11, array12)
print("Result of multiplication:")
print(result)


Array 10:
[[ 3 13 41]
 [36 14 18]
 [43 29 33]]
Determinant: 12559.99999999999
Inverse:
[[-0.00477707  0.06050955 -0.02707006]
 [-0.03296178 -0.13248408  0.11321656]
 [ 0.03519108  0.03757962 -0.0339172 ]]
Eigenvalues: [ 79.16326657 -21.92769233  -7.23557424]
Eigenvectors:
[[-0.47929193 -0.74400852  0.43553674]
 [-0.46960032  0.61686786 -0.88369001]
 [-0.74145451  0.25675935  0.17146345]]
Transpose:
[[ 3 36 43]
 [13 14 29]
 [41 18 33]]
Array 11:
[[10  3  7]
 [ 9 26  9]]
Array 12:
[[47 35]
 [42 25]
 [37 25]]
Result of multiplication:
[[ 855  600]
 [1848 1190]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [22]:
# 1. Create a Numpy array of shape (3,3) with values from 1 to 9
array1 = np.arange(1, 10).reshape(3, 3)
print("Array 1:")
print(array1)
 
# 1. Reshape the array to shape (1,9) and then to shape (9,1)
array1_reshaped1 = array1.reshape(1, 9)
print("Reshaped Array 1 (1,9):")
print(array1_reshaped1)
array1_reshaped2 = array1.reshape(9, 1)
print("Reshaped Array 1 (9,1):")
print(array1_reshaped2)


# 2. Create a Numpy array of shape (5,5)filled with random integers.
array2 = np.random.randint(1, 101, size=(5, 5))
print("Array 2:")
print(array2)

# 2. Flatten the array and then reshape it back to (5,5)
array2_flattened = array2.flatten()
print("Flattened Array 2:")
print(array2_flattened)
array2_reshaped = array2_flattened.reshape(5, 5)
print("Reshaped Array 2 (5,5):")
print(array2_reshaped)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped Array 1 (1,9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped Array 1 (9,1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Array 2:
[[ 3 30  3  7 77]
 [20 17  9 98 96]
 [85 37 53 60 43]
 [72 80 98 24 80]
 [97 81 83 33 30]]
Flattened Array 2:
[ 3 30  3  7 77 20 17  9 98 96 85 37 53 60 43 72 80 98 24 80 97 81 83 33
 30]
Reshaped Array 2 (5,5):
[[ 3 30  3  7 77]
 [20 17  9 98 96]
 [85 37 53 60 43]
 [72 80 98 24 80]
 [97 81 83 33 30]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [25]:
# 1. Create a Numpy array of shape (5,5) filled with random integers.
array3 = np.random.randint(1, 26, size=(5, 5))
print("Array 3:")
print(array3)

# 1. Use fancy indexing to extract the elements at the corners of the array.
corners = array3[[0, 0, 4, 4], [0, 4, 0, 4]]
print("Corners of Array 3:")
print(corners)

# 2. Create a Numpy array of shape (4,4) filled with random integers.
array4 = np.random.randint(1, 26, size=(4, 4))
print("Array 4:")
print(array4)

# 2. Use boolean indexing to set all elements greater than 10 to 10.
array4[array4 > 10] = 10
print("Array 4 after setting elements > 10 to 10:")
print(array4)

Array 3:
[[ 8 18 16  4  8]
 [ 4  6  3 21 13]
 [15  3  7 13  4]
 [19  3  5  9 18]
 [16  1 11  6 18]]
Corners of Array 3:
[ 8  8 16 18]
Array 4:
[[ 2  5 20  6]
 [16 21 18 19]
 [ 6 21  4  7]
 [ 9 14 14  3]]
Array 4 after setting elements > 10 to 10:
[[ 2  5 10  6]
 [10 10 10 10]
 [ 6 10  4  7]
 [ 9 10 10  3]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [26]:
# 1. Create a structured array with fields 'name'(String) and 'age' (integer), and 'height' (float).
dtype = np.dtype([('name', 'U10'), ('age', 'i4'), ('height', 'f4')])
array5 = np.array([('Alice', 25, 5.5), ('Bob', 30, 6.0), ('Charlie', 35, 5.8)], dtype=dtype)
print("Array 5:")
print(array5)

# 1. Add some data and sort the array by age.
new_data = np.array([('David', 28, 5.9)], dtype=dtype)
array5 = np.append(array5, new_data)
array5 = np.sort(array5, order='age')
print("Names in Array 5:")
print(array5['name'])


# 2. Create a structured array with fields 'X' and 'Y' (both integers).
dtype2 = np.dtype([('X', 'i4'), ('Y', 'i4')])
array6 = np.array([(1, 2), (3, 4), (5, 6)], dtype=dtype2)
print("Array 6:")
print(array6)

# 2. Add some data and compute the Euclidean distance between each pair of points.
new_points = np.array([(7, 8), (9, 10)], dtype=dtype2)
array6 = np.append(array6, new_points)
print("Array 6 after adding new points:")
print(array6)

# Compute Euclidean distance between each pair of points
def compute_distance(point1, point2):
    return np.sqrt((point1['X'] - point2['X'])**2 + (point1['Y'] - point2['Y'])**2)

distances = []
for i in range(len(array6)):
    for j in range(i + 1, len(array6)):
        dist = compute_distance(array6[i], array6[j])
        distances.append((array6[i], array6[j], dist))

print("Euclidean distances between points:")
for p1, p2, dist in distances:
    print(f"Distance between {p1} and {p2} is {dist}")
    

Array 5:
[('Alice', 25, 5.5) ('Bob', 30, 6. ) ('Charlie', 35, 5.8)]
Names in Array 5:
['Alice' 'David' 'Bob' 'Charlie']
Array 6:
[(1, 2) (3, 4) (5, 6)]
Array 6 after adding new points:
[(1,  2) (3,  4) (5,  6) (7,  8) (9, 10)]
Euclidean distances between points:
Distance between (1, 2) and (3, 4) is 2.8284271247461903
Distance between (1, 2) and (5, 6) is 5.656854249492381
Distance between (1, 2) and (7, 8) is 8.48528137423857
Distance between (1, 2) and (9, 10) is 11.313708498984761
Distance between (3, 4) and (5, 6) is 2.8284271247461903
Distance between (3, 4) and (7, 8) is 5.656854249492381
Distance between (3, 4) and (9, 10) is 8.48528137423857
Distance between (5, 6) and (7, 8) is 2.8284271247461903
Distance between (5, 6) and (9, 10) is 5.656854249492381
Distance between (7, 8) and (9, 10) is 2.8284271247461903


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [27]:
# 1. Create a masked array of shape (4,4) filled with random integers.
array7 = np.random.randint(1, 26, size=(4, 4))
print("Array 7:")
print(array7)

# 1. Mask the elements greater than 10. Compute the sum of the unmasked elements.
masked_array = np.ma.masked_array(array7, mask=array7 > 10)
print("Masked Array (values > 10 are masked):")
print(masked_array)
print("Sum of unmasked elements:")
print(masked_array.sum())

# 2. Create a masked array of shape (3,3) with random integers and mask the diagonal elements. 
# Replace the masked elements with the mean of the the unmasked elements.
array8 = np.random.randint(1, 26, size=(3, 3))
print("Array 8:")
print(array8)
masked_array2 = np.ma.masked_array(array8, mask=np.eye(3, dtype=bool))
print("Masked Array 2 (diagonal elements are masked):")
print(masked_array2)
masked_array2 = masked_array2.filled(masked_array2.mean())
print("Masked Array 2 after replacing masked elements with mean:")
print(masked_array2)    


Array 7:
[[25 15  8 24]
 [25 16  9 10]
 [13  8 19 14]
 [21 25 21 20]]
Masked Array (values > 10 are masked):
[[-- -- 8 --]
 [-- -- 9 10]
 [-- 8 -- --]
 [-- -- -- --]]
Sum of unmasked elements:
35
Array 8:
[[22  6  2]
 [10 12 11]
 [ 1  1  3]]
Masked Array 2 (diagonal elements are masked):
[[-- 6 2]
 [10 -- 11]
 [1 1 --]]
Masked Array 2 after replacing masked elements with mean:
[[ 5  6  2]
 [10  5 11]
 [ 1  1  5]]
